import {
  Home, Waves, Umbrella, UtensilsCrossed, ShoppingBag, Landmark, PartyPopper,
  Map, Bus, Recycle, ClipboardList, TriangleAlert, Phone, MessageCircle,
  BedDouble, KeyRound, Wifi, SquareParking, Leaf, Flame, Sparkles,
  Sailboat, Anchor, Shell, Fish, Pizza, Wine, Coffee, Croissant, Beer,
  Pill, Store, Mailbox, ShoppingCart, Church, Image, Drama, Camera, Castle,
  Volleyball, Bike, Mountain, Dumbbell, Backpack, Car, Train, Ship,
  Gift, Cake, Gem, GraduationCap,
  type LucideIcon,
} from 'lucide-react'

// Icone delle 14 sezioni di sistema (vedi sezioni.ts) + set esteso per le sezioni
// custom del superadmin (SezioniExtra.tsx). Chiave = valore salvato in `icona`
// (sezioni.ts, o colonna sezioni_extra.icona); un valore non riconosciuto (es. una
// vecchia emoji salvata prima di questo cambio) ricade sull'icona generica (Icona.tsx).
export const ICONE: Record<string, LucideIcon> = {
  home: Home,
  waves: Waves,
  umbrella: Umbrella,
  'utensils-crossed': UtensilsCrossed,
  'shopping-bag': ShoppingBag,
  landmark: Landmark,
  'party-popper': PartyPopper,
  map: Map,
  bus: Bus,
  recycle: Recycle,
  'clipboard-list': ClipboardList,
  'triangle-alert': TriangleAlert,
  phone: Phone,
  'message-circle': MessageCircle,
  'bed-double': BedDouble,
  'key-round': KeyRound,
  wifi: Wifi,
  'square-parking': SquareParking,
  leaf: Leaf,
  flame: Flame,
  sparkles: Sparkles,
  sailboat: Sailboat,
  anchor: Anchor,
  shell: Shell,
  fish: Fish,
  pizza: Pizza,
  wine: Wine,
  coffee: Coffee,
  croissant: Croissant,
  beer: Beer,
  pill: Pill,
  store: Store,
  mailbox: Mailbox,
  'shopping-cart': ShoppingCart,
  church: Church,
  image: Image,
  drama: Drama,
  camera: Camera,
  castle: Castle,
  volleyball: Volleyball,
  bike: Bike,
  mountain: Mountain,
  dumbbell: Dumbbell,
  backpack: Backpack,
  car: Car,
  train: Train,
  ship: Ship,
  gift: Gift,
  cake: Cake,
  gem: Gem,
  'graduation-cap': GraduationCap,
}

// Righe tematiche per il selettore icone in SezioniExtra.tsx (superadmin).
export const ICONE_SCELTA: string[][] = [
  ['home', 'bed-double', 'key-round', 'wifi', 'square-parking', 'leaf', 'flame', 'sparkles'],
  ['waves', 'umbrella', 'sailboat', 'anchor', 'shell', 'fish'],
  ['utensils-crossed', 'pizza', 'wine', 'coffee', 'croissant', 'beer'],
  ['shopping-bag', 'pill', 'store', 'mailbox', 'shopping-cart'],
  ['landmark', 'church', 'image', 'drama', 'camera', 'castle'],
  ['party-popper', 'volleyball', 'bike', 'mountain', 'dumbbell', 'backpack'],
  ['map', 'bus', 'car', 'train', 'ship'],
  ['recycle', 'clipboard-list', 'triangle-alert', 'phone', 'gift', 'cake', 'gem', 'graduation-cap'],
]
